theme: jekyll-theme-cayman
themeCustom: 
  body-background-color: 'f0f8df'
  body-color: '2E5519'
  head-background-color: '96C927'
  head-color: 'f1ffe7'
  hx-color: '82BA1B'
  menu-background-color: 'D7F6C0'
  menu-title-color: '82BA1B'
  menu-color: '1F5615'
nameLogo: script_icon.png
jeedomColor: 96c927

#memo pour dev th√®me
memo: 
  body-background-color: '041453'  
  body-color: 'A7C2FF'  
  head-background-color: '133176'  
  head-color: '79b0f6'  
  hx-color: '457CDF'  
  menu-background-color: '080E49'  
  menu-color: '4F71C2'  
  menu-title-color: 'a9cfff'
<<<<<<< HEAD
version: 201712221127
=======
version: 201712221058
>>>>>>> 18585b533c33f1ad02b5d3a1cab3ba235d920677
